#!/usr/bin/env python

import os, sys, time, shutil

class condorSubmiter:
  def __init__(self,job_name) :
    self.time_s = time.strftime("_%d%b%Y_%HH%MM",time.localtime())
    self.run_dir = job_name+self.time_s
    os.mkdir(self.run_dir)
    os.chdir(self.run_dir)
    self.jds_s = """
executable  = %s
universe    = vanilla
error = %s_error.txt
log = %s_log.txt
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = %s
queue
"""

  def getRunDir(self):
    return self.run_dir
 
  def setJobtype(self, jop_type):
    self.job_type = job_type

  def setJobname(self, job_name):
    self.job_name = job_name 

  def setJobnumber(self, job_number):
    self.job_number = job_number

  def setCMSpath(self, cms_path):
    self.cms_path = cms_path

  def setCMS(self,cms_set):
    self.cms_set = cms_set
  
    if cms_set:
      self.sh_s = """#!/bin/bash
MYPWD=${PWD}
source /cvmfs/cms.cern.ch/cmsset_default.sh
cd %s
eval `scramv1 runtime -sh`
export LHAPDFSYS=/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/lhapdf/6.1.5/
export PATH=${PATH}:${LHAPDFSYS}/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${LHAPDFSYS}/lib
export LHAPATH=/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/lhapdf/6.1.5/share/LHAPDF
cd $MYPWD
host=`hostname`
MYDIR="%s"
/bin/mkdir  -p $MYDIR
cd $MYDIR
cp /cms/scratch/hyunyong/rivet/src/rivetTools/powheg/powheg2.tar .
tar -xf powheg2.tar
cd POWHEG-BOX-V2/dijet/
make -j 8
cd ../../
cp /cms/scratch/hyunyong/rivet/src/rivetTools/powheg/dijet_CT10_13TeV.input .
sed -e s/SEED/%d/g dijet_CT10_13TeV.input > powheg.input 
POWHEG-BOX-V2/dijet/pwhg_main
      """
  def addexe(self, cmd_string):
    self.sh_s += "\n%s"%cmd_string
  def submit(self, cmd_string):
    job_dir = self.job_name+"_%03d"%self.job_number
    if self.cms_set:
      tmp_sh_s = self.sh_s%(self.cms_path,job_dir+self.time_s, self.job_number)
    tmp_sh = open(job_dir+".sh", "w")
    tmp_sh.write(tmp_sh_s)
    tmp_sh.close()
    tmp_jds_s = self.jds_s%(job_dir+".sh", job_dir, job_dir, job_dir+self.time_s)
    tmp_jds = open(job_dir+".jds", "w")
    tmp_jds.write(tmp_jds_s)
    tmp_jds.close()
    os.system("chmod 755 %s.sh"%job_dir)
    os.system("chmod 755 %s.jds"%job_dir)
    os.system("condor_submit %s.jds"%job_dir)

if __name__ == "__main__" :

  cmssw_set = "cms_set_on"
  cmssw_path = "/cms/scratch/hyunyong/rivet/src"
  job_type = "/cms/scratch/hyunyong/rivet/src/rivetTools/powheg/POWHEG-BOX/Dijet/pwhg_main"
  #exe_l = sys.argv[1]

  #teve = int(sys.argv[2])
  #pt_min = int(sys.argv[3])
  #pt_max = int(sys.argv[4])
  #job_tag = sys.argv[5]
  #if teve < 100:
  #  njob = 1
  #else:
  #  njob = 100

  i_path = os.getcwd()
  cs = condorSubmiter("POWHEG_2jet")
  if not cmssw_set.startswith("cms_set"):
    print "cms_set error, input cms_set_on or cms_set_off"
    sys.exit()
  elif cmssw_set == "cms_set_on":
    cs.setCMS(True)
    cs.setCMSpath(cmssw_path)
  else:
    cs.setCMS(Flase)
  cs.setJobtype(job_type)
  cs.setJobname("POWHEG_2jet")
  #cs.addexe("python %s ."%(os.environ['CMSSW_BASE']+"/src/rivetTools/yoda2root3.py"))

  #shutil.copy2("../"+exe_l, exe_l)
  #shutil.copy2(os.environ['CMSSW_BASE']+"/src/GeneratorInterface/RivetInterface/src/cc_ana.cc", "cc_ana.cc")
  #log_set = open("run_set.log","w")
  #log_set.write("Job Tag : %s\n"%job_tag)
  #log_set.write("Dir name : %s\n"%cs.getRunDir())
  #log_set.write("Total events number : %s\n"%format(teve,',d'))
  #log_set.write("pT set : %d - %d GeV\n"%(pt_min,pt_max))
  #log_set.write("Execute file : %s\n"%exe_l)
  #log_set.close()
  for i in xrange(100):
    cs.setJobnumber(i+1)
    cs.submit("%s"%(job_type))




  
